# Generated by Django 4.0.4 on 2022-05-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_data_age_alter_data_apellidos_alter_data_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.CharField(auto_created=True, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
